name: GlendonPlace
favicon: null
layout_spectrum: 0.33100275974720716
typography_spectrum: 0.4981828194577247
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.133432328235358
  lightness: 0.17467650678008795
  saturation: 0.7338417498394847
  rhythmicContrast: 0.5242407920304686
purpose: []
